[project]
name = "proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "flask>=3.1.1",
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
    "uvicorn>=0.35.0",
]
